name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run Tests
        run: docker-compose down && docker-compose up -d

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker-compose push ${{ secrets.DOCKERHUB_USERNAME }}